public class REST_PostalApiWrapper {

	public String Message;	    //Number of Post office(s) found: 10
	public String Status;	    //Success
	public List<PostOffice> PostOffice;
	class PostOffice {
		public String Name;	    //Alanda
		public String Description;	    //
		public String BranchType;	    //Branch Post Office
		public String DeliveryStatus;	    //Delivery
		public String Taluk;	    //Rajgangpur
		public String Circle;	    //Rajgangpur
		public String District;	    //Sundergarh
		public String Division;	    //Sundargarh
		public String Region;	    //Sambalpur
		public String State;	    //Odisha
		public String Country;	    //India
	}


}